### PR TITLE
Fix incorrect signatures in `.pyi` stubs 

### LINKED ISSUE #129: `AggregatedTranscript()` signature incorrect in `.pyi`
`ferveo/__init__.pyi` has:

```
class AggregatedTranscript:

    def __init__(self, messages: Sequence[Tuple[Validator, Transcript]]):
        ...
```

But `AggregatedTranscript::new` is defined in the bindings as 

```
#[pymethods]
impl AggregatedTranscript {
    #[new]
    pub fn new(messages: Vec<ValidatorMessage>) -> Self {
```

where `ValidatorMessage` is not exported. 

Same problem with `AffregatedTranscript.verify()` and `Dkg.aggregate_transcripts()`. This is also repeated in the copy of the type stubs in `nucypher-core`.

### PR DESCRIPTION
**Pull request by piotr-roslaniec**
**Type of PR:**
- Bugfix

**Required reviews:** 
- 1

**What this does:**
- Updates the definition of `ValidatorMessage` in Python bindings
- Replaces former usage in `.pyi` file, examples, etc.

**Issues fixed/closed:**
- Fixes #129

**Why it's needed:**
- To provide correct type hints and concrete types in Python bindings

**Notes for reviewers:**
 - Based on #128 
 - Downstream changes addressed in https://github.com/nucypher/nucypher-core/pull/65

### CODE REVIEW

**Comment by derekpierre** [comment]
If this is will affect `nucypher`/`nucypher-core` downstream, we should have a parallel `nucypher-core`/`nucypher` open PR before this is merged. Presumably, you can install the updated ferveo module locally for downstream development...?

No use in merging/releasing this code etc. to then catch problems in `nucypher-core`/`nucypher` for which a `ferveo` fix is needed.

**Comment by derekpierre** [comment]
Although I guess it looks like this goes into a feature branch `fix-dkg-pk-deser-wasm` *before* merging into `main`...if that's the case then I stand corrected.

**Comment by derekpierre** [comment]
Perfect 👌 !

> Order of feedback: nucypher => nucypher-core => ferveo
> Order of merging: Same

Order of merging the PRs once reviewed and working would be:
1. merge `ferveo` changes
2. update `ferveo` dependency, and merge `nucypher-core` changes, then release
3. update `nucypher-core` release dependency and merge `nucypher`

**Review by KPrasch — APPROVED** [review]
👨🏻‍🚀

**Review by derekpierre — APPROVED** [review]
🎸

**Pull request merged**
