### PR TITLE
Hide `DkgPublicParams` from external API

### PR DESCRIPTION
**Pull request by piotr-roslaniec**
**Type of PR:**
- Feature

**Required reviews:**
-  1

**What this does:**
- Removes `DkgPublicKey` from public API (bindings) and replaces it with a default value internally

**Why it's needed:**
- Simplifies user API

**Notes for reviewers:**
- Previously discussed [on Discord](https://discord.com/channels/411401661714792449/412681039178366996/1118171002824822925)

### CODE REVIEW

**Comment by theref** [comment]
love this 🪓

**Comment by derekpierre** [comment]
Will this have downstream effects in `nucypher-core`/`nucypher`?

**Comment by piotr-roslaniec** [comment]
From the perspective of `nucypher-core` etc this is not a breaking change since related bindings are not used anywhere directly, they are just re-exported from `nucypher-core` instead.

From the perspective of `nucypher` it may cause some changes - I imagine this API is at the least used in tests.

I can create issues to track these changes where needed.

**Comment by derekpierre** [comment]
> I can create issues to track these changes where needed.

👍 - It would be good to have these filed / tracked, and owned by someone.

**Pull request merged**
